[package]
name = "lucid"
description = "A Fast, Secure and Distributed KV store with a HTTP API."
version = "0.1.2"
authors = ["Clint.Network <me@clint.network>"]
edition = "2018"
keywords = ["kv", "distributed", "ledger", "kv-store", "key-value", "rest", "http", "swagger", "websocket"]
repository = "https://github.com/clintnetwork/lucid"
license = "https://github.com/clintnetwork/lucid/blob/master/LICENSE.md"
build = "build.rs"

[package.metadata.winres]
LegalCopyright = "Copyright Â© 2019 Lucid - All Rights Reserved"

[badges]
travis-ci = { repository = "clintnetwork/lucid", branch = "master" }

[build-dependencies]
winres = "*"

[dependencies]
nickel = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
serde_yaml = "*"
rustflake = "*"
chrono = "*"
include_dir = "*"
jsonwebtoken = "*"
app_dirs = "*"
colored = "*"
yaml-rust = "*"
ring = "*"
uuid = "*"
rand = "*"
warp = "*"
chashmap = "*"
plugin = "*"
#hyper = "*"
#hyper-openssl = "*"

[dependencies.clap]
version = "*"
features = ["yaml"]