[package]
name = "lucid"
version = "0.1.0"
authors = ["Clint.Network <me@clint.network>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
